name: babelify
on:
  # Workaround for syncing browser/gotrue.js on release-please PRs
  push:
    branches:
      - release-*
jobs:
  babelify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.NODE_PKG_RELEASE_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install dependencies
        run: npm ci
      - run: npm run babelify
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: sync browser/gotrue.js'
